
--Mysql

--Section 1

--Quetion 1

SELECT EVENTREQUEST.EVENTNO, DATEHELD, COUNT(*) AS COUNTEVENTPLAN
	FROM EVENTREQUEST, EVENTPLAN
	WHERE EVENTREQUEST.EVENTNO = EVENTPLAN.EVENTNO
	AND DATEHELD BETWEEN '2013-12-01' AND '2013-12-31'
	GROUP BY EVENTREQUEST.EVENTNO
	HAVING COUNT(*) > 1 ;

-- Question 2
SELECT PLANNO, EVENTPLAN.EVENTNO, WORKDATE, ACTIVITY
	FROM EVENTPLAN, FACILITY,EVENTREQUEST
	WHERE WORKDATE BETWEEN '2013-12-01' AND '2013-12-31'
	AND FACNAME = 'Basketball arena'
	AND EVENTPLAN.EVENTNO = EVENTREQUEST.EVENTNO
	AND EVENTREQUEST.FACNO = FACILITY.FACNO;

-- Question 3

SELECT EVENTREQUEST.EVENTNO, DATEHELD, STATUS, ESTCOST
	FROM EVENTREQUEST,FACILITY,EMPLOYEE,EVENTPLAN
	WHERE DATEHELD BETWEEN '2013-10-01' AND '2013-12-31'
	AND EMPNAME = 'Mary Manager'
	AND FACNAME = 'Basketball arena'
	AND EVENTREQUEST.EVENTNO = EVENTPLAN.EVENTNO
	AND EVENTPLAN.EMPNO = EMPLOYEE.EMPNO
	AND EVENTREQUEST.FACNO = FACILITY.FACNO;

-- Question 4

SELECT EVENTPLANLINE.PLANNO, LINENO, RESNAME,NUMBERFLD,LOCNAME,TIMESTART, TIMEEND
	FROM EVENTPLANLINE,LOCATION,FACILITY,EVENTPLAN,RESOURCETBL
	WHERE WORKDATE BETWEEN '2013-10-01' AND '2013-12-31'
	AND ACTIVITY = 'Operation'
	AND FACNAME = 'Basketball arena'
	AND EVENTPLAN.PLANNO = EVENTPLANLINE.PLANNO
	AND EVENTPLANLINE.LOCNO = LOCATION.LOCNO
	AND EVENTPLANLINE.RESNO = RESOURCETBL.RESNO
	AND LOCATION.FACNO = FACILITY.FACNO;

--Section 2

-- Question 1

INSERT INTO FACILITY VALUES ('F104','Swimming Pool');

-- Question 2

INSERT INTO LOCATION VALUES ('L107','F104','Door');


--Question 3


INSERT INTO LOCATION VALUES ('L108','F104','Locker Room');


--Question 4

UPDATE LOCATION
	SET LOCNAME = 'Gate'
	WHERE LOCNAME = 'Door';

--Question 5

DELETE FROM LOCATION
 WHERE LOCNO = 'L108';
	

