--DML Module 4

--1

SELECT  DISTINCT CITY,STATE, ZIP
	FROM CUSTOMER;

--2
SELECT EMPNAME, DEPARTMENT, PHONE, EMAIL 
	FROM EMPLOYEE
	WHERE PHONE LIKE '3%';

--3
SELECT * FROM RESOURCETBL
	WHERE RATE BETWEEN '10' AND '20'
	ORDER BY RATE;

--4
SELECT EVENTNO, DATEAUTH, STATUS
	FROM EVENTREQUEST
	WHERE STATUS IN ('Approved','Denied') AND
	DATEAUTH BETWEEN '2013-07-01' AND '2013-07-31';


--5
SELECT LOCNO, LOCNAME
	FROM LOCATION, FACILITY
	WHERE FACNAME = 'Basketball arena' AND
	LOCATION.FACNO = FACILITY.FACNO;

--6
SELECT PLANNO, COUNT(LINENO) AS LINECOUNT, SUM(NUMBERFLD) AS SUMRESONO
	FROM EVENTPLANLINE
	GROUP BY PLANNO
	HAVING COUNT(LINENO) >= 1 ;


