
--Mysql Module 5

--Question 1

SELECT EVENTNO, DATEHELD, CUSTOMER.CUSTNO, CUSTNAME, FACILITY.FACNO, FACNAME
	FROM EVENTREQUEST, CUSTOMER, FACILITY
	WHERE DATEHELD BETWEEN '2013-01-01' AND '2013-12-31'
	AND CITY = 'Boulder'
	AND CUSTOMER.CUSTNO = EVENTREQUEST.CUSTNO
	AND FACILITY.FACNO = EVENTREQUEST.FACNO;

--Question 2

SELECT CUSTOMER.CUSTNO,CUSTNAME, EVENTNO, DATEHELD, FACILITY.FACNO, FACNAME, ESTCOST/ESTAUDIENCE AS COSTPERPEROSON 
	FROM EVENTREQUEST, CUSTOMER,FACILITY
	WHERE ESTCOST/ESTAUDIENCE < 0.2
	AND EVENTREQUEST.CUSTNO = CUSTOMER.CUSTNO
	AND  EVENTREQUEST.FACNO = FACILITY.FACNO;


--Question 3	

SELECT CUSTOMER.CUSTNO, CUSTNAME, SUM(ESTCOST) AS TOTALAMOUNT
	FROM EVENTREQUEST, CUSTOMER
	WHERE STATUS = 'Approved'
	GROUP BY CUSTOMER.CUSTNO, CUSTNAME;


--Question 4

INSERT INTO CUSTOMER VALUES ('C108','Wut Hmone','MMU','Y','Hnin Hlaing','011-2888888', 'Cyberjaya','SG','63100');


-- Question 5

UPDATE RESOURCETBL
	SET RATE = RATE + (RATE*0.1)
	WHERE RESNAME = 'nurse';

-- Question 6

DELETE FROM CUSTOMER
	WHERE CUSTNO = 'C108';