


CREATE TABLE EMPLOYEE (
EMPNO VARCHAR(8)  NOT NULL,
EMPNAME VARCHAR(30) NOT NULL,
DEPARTMENT VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
PHONE VARCHAR(6) NOT NULL,
PRIMARY KEY (EMPNO)
);


CREATE TABLE CUSTOMER (
	CUSTNO VARCHAR(8) NOT NULL,
	CUSTNAME VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(30) NOT NULL,
	INTERNAL CHAR(1) NOT NULL,
	CONTACT VARCHAR(30) NOT NULL,
	PHONE VARCHAR(30) NOT NULL,
	CITY VARCHAR(30) NOT NULL,
	STATE CHAR(2) NOT NULL,
	ZIP VARCHAR(5) NOT NULL,
	 PRIMARY KEY  (CUSTNO)
);

CREATE TABLE RESOURCETBL(
	RESNO VARCHAR(8)  NOT NULL,
	RESNAME VARCHAR(30) NOT NULL,
	RATE VARCHAR(30) NOT NULL CHECK (RATE>0),
	PRIMARY KEY (RESNO)
);

CREATE TABLE FACILITY (
	FACNO VARCHAR(8)  NOT NULL,
	FACNAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (FACNO)
);

CREATE TABLE LOCATION (
	LOCNO VARCHAR(8) NOT NULL,
	FACNO VARCHAR(30),
	LOCNAME VARCHAR(30),
	PRIMARY KEY (LOCNO)

);

CREATE TABLE EVENTREQUEST (
	EVENTNO VARCHAR(8)   NOT NULL,
	DATEHELD DATE NOT NULL,
	DATEREQ DATE NOT NULL,
	CUSTNO VARCHAR(8) NOT NULL,
	FACNO VARCHAR(8) NOT NULL,
	DATEAUTH DATE ,
	STATUS VARCHAR(30) CHECK ('Pending' OR 'Denied' OR'Approved' ) ,
	ESTCOST INTEGER,
	ESTAUDIENCE INTEGER CHECK (ESTAUDIENCE>0),
	BUDNO VARCHAR(8),
	PRIMARY KEY (EVENTNO),
	CONSTRAINT FKCUSTNO FOREIGN KEY (CUSTNO)  REFERENCES CUSTOMER ,
	CONSTRAINT FKFACNO FOREIGN KEY (FACNO)  REFERENCES FACILITY
);

CREATE TABLE EVENTPLAN (
	PLANNO VARCHAR(8)  NOT NULL,
	EVENTNO VARCHAR(8) NOT NULL,
	WORKDATE DATE NOT NULL,
	NOTES VARCHAR (50),
	ACTIVITY VARCHAR(30) NOT NULL,
	EMPNO VARCHAR(8) ,
	PRIMARY KEY (PLANNO),
	CONSTRAINT FKEMPNO FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE
);

CREATE TABLE EVENTPLANLINE (
	PLANNO VARCHAR(8)NOT NULL,
	LINENO  INTEGER NOT NULL,
	TIMESTART DATETIME NOT NULL,
	TIMEEND DATETIME NOT NULL CHECK ( TIMEEND > TIMESTART),
	NUMBERFLD INTEGER  NOT NULL,
	LOCNO VARCHAR(8) NOT NULL,
	RESNO VARCHAR(8) NOT NULL,
	CONSTRAINT PKEVENTPLANLINE PRIMARY KEY (PLANNO,LINENO),
	CONSTRAINT FKLOCNO FOREIGN KEY (LOCNO) REFERENCES LOCATION,
	CONSTRAINT FKRESNO FOREIGN KEY (RESNO) REFERENCES RESOURCETBL
);